---
# sample ansible-playbook script to install snark dependencies and build snark from source; include it as it is or copy to your playbook

# todo: install more dependencies and turn on corresponding cmake switches snark_build_... ON

- hosts: localhost
  connection: local
  vars:
  - make_j: 6
  - base: "{{ ansible_env.HOME }}"
  - snark_cmake_options: "-DBUILD_TESTS=ON -DINSTALL_TESTS=ON -DINSTALL_BASH_COMPLETION=ON -Dsnark_build_control=ON -Dsnark_build_graph=ON -Dsnark_build_graphics=ON -Dsnark_build_math_fft=ON -Dsnark_build_geometry=ON -Dsnark_build_point_cloud=ON -Dsnark_build_sensors_dc1394=ON -Dsnark_build_sensors_velodyne=ON -Dsnark_build_sensors_vimba=ON -Dsnark_build_web=ON -Dsnark_build_web_feeds=ON -Dsnark_build_imaging=ON -Dsnark_build_imaging_stereo=OFF"

  tasks:
  - name: "snark: dependencies: installing"
    become: true
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
      - libeigen3-dev
      - libtbb-dev
      - zlib1g-dev
      - libbz2-dev
      - libopencv-dev 
      - libopencv-highgui-dev
      - libpcap-dev
      - qtbase5-dev 
      - qt5-default 
      - qt3d5-dev
      - python-opencv
      - libqt4-dev

  - name: "snark: dependencies: vimba: download"
    get_url:
        url: "https://cdn.alliedvision.com/fileadmin/content/software/software/Vimba/Vimba_v2.1.3_Linux.tgz"
        dest: "/tmp/Vimba_v2.1.3_Linux.tgz"

  - name: "snark: dependencies: vimba: extract"
    unarchive:
        src: "/tmp/Vimba_v2.1.3_Linux.tgz"
        dest: "/opt"
    become: true

  - name: "snark: dependencies: vimba: library symlink"
    file:
        dest: /opt/vimba
        src: /opt/Vimba_2_1
        state: link
    become: true
    
  - name: "snark: dependencies: vimba: VimbaViever symlink"
    file:
        dest: /usr/local/bin/vimba-viewer
        src: /opt/vimba/Tools/Viewer/Bin/x86_64bit/VimbaViewer
        state: link
    become: true

  - name: "snark: dependencies: vimba: running install"
    command: chdir=/opt/vimba/VimbaGigETL ./Install.sh
    become: true
      
  - name: "snark: make source directory at {{ base }}"
    file: path={{ base }}/{{ item }} state=directory
    with_items:
        - src
        - build
      
  - name: "snark: dependencies: clone comma"
    git:
        repo: "https://gitlab.com/orthographic/comma.git"
        dest: "{{ base }}/src/comma"
        clone: yes
        update: yes
      
  - name: "snark: dependencies: install comma"
    script: /usr/bin/ansible-playbook {{ base }}/src/comma/system/ansible/install.yml
    
  - name: "snark: clone"
    git:
        repo: "https://gitlab.com/orthographic/snark.git"
        dest: "{{ base }}/src/snark"
        clone: yes
        update: yes
        
  - name: "snark: make build directory at {{ base }}"
    file: dest="{{ base }}/build/snark" state=directory

  - name: "snark: cmake"
    shell: "/usr/bin/cmake {{ snark_cmake_options }} {{ base }}/src/snark chdir={{ base }}/build/snark"

  - name: "snark: make"
    make:
        chdir: "{{ base }}/build/snark"
        params:
            MAKEFLAGS: "-j {{ make_j }}"

  - name: "snark: install"
    become: true
    make:
        chdir: "{{ base }}/build/snark"
        target: "install"
