---
# sample ansible-playbook script to install snark dependencies and build snark from source; include it as it is or copy to your playbook

- hosts: localhost
  connection: local
  vars:
  - build_j: 6
  - base: "{{ ansible_env.HOME }}"
  - snark_src_dir: "{{ base }}/src/snark"
  - snark_build_dir: "{{ base }}/build/snark"
  - snark_cmake_options: "-DBUILD_TESTS=ON -DINSTALL_TESTS=ON -DINSTALL_BASH_COMPLETION=ON -Dsnark_BUILD_XML=ON -Dsnark_BUILD_ZEROMQ=ON -Dsnark_INSTALL_WEB_SHELL=OFF"

  tasks:
  - name: "install snark dependencies"
    become: true
    apt: pkg={{ item }} state=present update_cache=yes
    with_items:
      - libeigen3-dev
      - libtbb-dev
      - zlib1g-dev
      - libbz2-dev
      - libopencv-dev 
      - libopencv-highgui-dev
      - libpcap-dev
      - qtbase5-dev 
      - qt5-default 
      - qt3d5-dev
      - python-opencv
      - libqt4-dev

  - name: "vimba: download"
    get_url:
        url: "https://cdn.alliedvision.com/fileadmin/content/software/software/Vimba/Vimba_v2.1.3_Linux.tgz"
        dest: "/tmp/Vimba_v2.1.3_Linux.tgz"

  - name: "vimba: extract"
    unarchive:
        src: "/tmp/Vimba_v2.1.3_Linux.tgz"
        dest: "/opt"
    become: true

  - name: "vimba: symlink 1/1"
    file:
        dest: /opt/vimba
        src: /opt/Vimba_2_1
        state: link
    become: true
    
  - name: "vimba: symlink 2/2"
    file:
        dest: /usr/local/bin/vimba-viewer
        src: /opt/vimba/Tools/Viewer/Bin/x86_64bit/VimbaViewer
        state: link
    become: true

  - name: "vimba: install"
    command: chdir=/opt/vimba/VimbaGigETL ./Install.sh
    become: true
      
  - name: "snark: make source directory at {{ base }}"
    file: path={{ base }}/{{ item }} state=directory
    with_items:
        - src
        - build
      
  - name: "snark: clone comma"
    git:
        repo: "https://gitlab.com/orthographic/comma.git"
        dest: "{{ base }}/src/comma"
        clone: yes
        update: yes
      
  - name: "snark: install comma"
    script: /usr/bin/ansible-playbook {{ base }}/src/comma/system/ansible/install.yml
    
  - name: "snark: clone"
    git:
        repo: "https://gitlab.com/orthographic/snark.git"
        dest: "{{ base }}/src/snark"
        clone: yes
        update: yes
        
  - name: "snark: make build directory at {{ base }}"
    file: dest="{{ snark_build_dir }}" state=directory

  - name: "snark: cmake"
    shell: "/usr/bin/cmake {{ snark_cmake_options }} {{ snark_src_dir }} chdir={{ snark_build_dir }}"

  - name: "snark: make"
    make:
        chdir: "{{ snark_build_dir }}"
        params:
            MAKEFLAGS: "-j {{ build_j }}"

  - name: "snark: install"
    become: true
    make:
        chdir: "{{ snark_build_dir }}"
        target: "install"
